name: Builder

on:
  push:
    paths:
      - 'source/**'
      - 'CMakeLists.txt'
  pull_request:
    paths:
      - 'source/**'
      - 'CMakeLists.txt'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install apt dependencies
      run: |
          sudo add-apt-repository -y ppa:tricksterguy87/complx
          sudo apt update -qq
          sudo apt install -y liblc3-dev liblc3-replay libwxgtk3.0-gtk3-dev

    - name: Make build files.
      run: |
        mkdir build && cd build
        cmake ..

    - name: Build and Install
      run: sudo cmake --build build --target install
